{% set version = "0.0-25" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tau
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tau_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tau/tau_{{ version }}.tar.gz
  sha256: ff22d4a633957479e0ecdb1c0223df09f9321017aade6a28b2f264fe7bbd8e90

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('tau')"           # [not win]
    - "\"%R%\" -e \"library('tau')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=tau
  license: GPL-2.0-or-later
  summary: Utilities for text analysis.
  license_family: GPL2
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
